version: v2.34.0

name: fintra

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

volumes:
  db:
