name: fintra

services:
  app:
    build: .
    environment:
      LOG_LEVEL: warning
      DATABASE_URL: postgresql://user:pass@db:5432/main
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'

volumes:
  db: {}
  prometheus-data: {}
