services:
  app:
    build: .
    container_name: starlette_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/main

  db:
    image: postgres:16
    container_name: starlette_db
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
